<?php

namespace ContainerJyK98ox;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QTUnXTpService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.qTUnXTp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qTUnXTp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'blogpostRepository' => ['privates', 'App\\Repository\\BlogpostRepository', 'getBlogpostRepositoryService', true],
            'chatRepository' => ['privates', 'App\\Repository\\ChatRepository', 'getChatRepositoryService', true],
        ], [
            'blogpostRepository' => 'App\\Repository\\BlogpostRepository',
            'chatRepository' => 'App\\Repository\\ChatRepository',
        ]);
    }
}
