<?php

namespace ContainerJyK98ox;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogpostControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\BlogpostController' shared autowired service.
     *
     * @return \App\Controller\BlogpostController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\BlogpostController'] = $instance = new \App\Controller\BlogpostController();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\BlogpostController', $container));

        return $instance;
    }
}
