<?php

namespace ContainerJyK98ox;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentaireTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\CommentaireType' shared autowired service.
     *
     * @return \App\Form\CommentaireType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\CommentaireType'] = new \App\Form\CommentaireType();
    }
}
