<?php

namespace ContainerJyK98ox;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarrousselRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CarrousselRepository' shared autowired service.
     *
     * @return \App\Repository\CarrousselRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CarrousselRepository'] = new \App\Repository\CarrousselRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
