<?php

namespace ContainerJyK98ox;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentaireServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\CommentaireService' shared autowired service.
     *
     * @return \App\Service\CommentaireService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\CommentaireService'] = new \App\Service\CommentaireService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['session.flash_bag'] ?? $container->load('getSession_FlashBagService')));
    }
}
