<?php

namespace ContainerJyK98ox;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ChatRepository' shared autowired service.
     *
     * @return \App\Repository\ChatRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ChatRepository'] = new \App\Repository\ChatRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
