<?php

namespace Container1DEoC7N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QA2EdxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q_a2Edx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q_a2Edx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'appAuthenticator' => ['privates', 'App\\Security\\AppAuthenticator', 'getAppAuthenticatorService', true],
            'authenticator' => ['privates', 'security.user_authenticator', 'getSecurity_UserAuthenticatorService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'appAuthenticator' => 'App\\Security\\AppAuthenticator',
            'authenticator' => '?',
            'passwordHasher' => '?',
        ]);
    }
}
