<?php

namespace ContainerKOz4xbf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IO8ceTaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IO8ceTa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IO8ceTa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorie' => ['privates', '.errored..service_locator.IO8ceTa.App\\Entity\\Categorie', NULL, 'Cannot autowire service ".service_locator.IO8ceTa": it references class "App\\Entity\\Categorie" but no such service exists.'],
            'chatRepository' => ['privates', 'App\\Repository\\ChatRepository', 'getChatRepositoryService', true],
        ], [
            'categorie' => 'App\\Entity\\Categorie',
            'chatRepository' => 'App\\Repository\\ChatRepository',
        ]);
    }
}
