<?php

namespace ContainerKOz4xbf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogpostService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.2hay1DI.App\Entity\Blogpost' shared service.
     *
     * @return \App\Entity\Blogpost
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.2hay1DI": it references class "App\\Entity\\Blogpost" but no such service exists.');
    }
}
