<?php

namespace ContainerKOz4xbf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentaireServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\CommentaireService' shared autowired service.
     *
     * @return \App\Service\CommentaireService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CommentaireService.php';

        return $container->privates['App\\Service\\CommentaireService'] = new \App\Service\CommentaireService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['session.flash_bag'] ?? $container->load('getSession_FlashBagService')));
    }
}
