<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJyK98ox\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJyK98ox/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJyK98ox.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJyK98ox\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerJyK98ox\App_KernelProdContainer([
    'container.build_hash' => 'JyK98ox',
    'container.build_id' => '8375b5f9',
    'container.build_time' => 1638301127,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJyK98ox');
