<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'a_propos' => [[], ['_controller' => 'App\\Controller\\AProposController::index'], [], [['text', '/a-propos']], [], []],
    'admin_dashboard' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin/dashboard']], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], []],
    'actualites' => [[], ['_controller' => 'App\\Controller\\BlogpostController::actualites'], [], [['text', '/actualites']], [], []],
    'actualites_detail' => [['slug'], ['_controller' => 'App\\Controller\\BlogpostController::detail'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/actualites']], [], []],
    'adoption' => [[], ['_controller' => 'App\\Controller\\ChatController::adoption'], [], [['text', '/adoption']], [], []],
    'chat_details' => [['nom'], ['_controller' => 'App\\Controller\\ChatController::details'], [], [['variable', '/', '[^/]++', 'nom', true], ['text', '/chats']], [], []],
    'compte' => [[], ['_controller' => 'App\\Controller\\CompteController::index'], [], [['text', '/compte']], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], []],
    'disparu' => [[], ['_controller' => 'App\\Controller\\DisparuController::index'], [], [['text', '/disparu']], [], []],
    'fa' => [[], ['_controller' => 'App\\Controller\\FaController::index'], [], [['text', '/fa']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'libre' => [[], ['_controller' => 'App\\Controller\\LibreController::index'], [], [['text', '/libre']], [], []],
    'mention' => [[], ['_controller' => 'App\\Controller\\MentionController::index'], [], [['text', '/mention']], [], []],
    'parrain' => [[], ['_controller' => 'App\\Controller\\ParrainController::index'], [], [['text', '/parrain']], [], []],
    'partenaire' => [[], ['_controller' => 'App\\Controller\\PartenaireController::index'], [], [['text', '/partenaire']], [], []],
    'portfolio' => [[], ['_controller' => 'App\\Controller\\PortfolioController::index'], [], [['text', '/chatCategorie']], [], []],
    'portfolio_categorie' => [['slug'], ['_controller' => 'App\\Controller\\PortfolioController::categorie'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/portfolio']], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\RegisterController::register'], [], [['text', '/inscription']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/deconnexion']], [], []],
];
