<?php

namespace Container4MMedxp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gvoIr1F.App\Entity\Chat' shared service.
     *
     * @return \App\Entity\Chat
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.gvoIr1F": it references class "App\\Entity\\Chat" but no such service exists.');
    }
}
