<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.8c994506.js',
                '/build/761.e2f71788.js',
                '/build/app.cde53ada.js',
            ],
            'css' => [
                '/build/761.0bc1c5f1.css',
                '/build/app.b2c0d4dc.css',
            ],
        ],
    ],
],

]];
