<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \App\Entity\Utilisateur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'cp', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'accueil', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'nb', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'animaux', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'sterilise', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'chat', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'quarantaine', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'journee', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'vacances', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'libre', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'assurance', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'veto', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'autre', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'non'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'roles', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'cp', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'accueil', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'nb', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'animaux', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'sterilise', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'chat', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'quarantaine', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'journee', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'vacances', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'libre', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'assurance', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'veto', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'autre', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'non'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Utilisateur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserIdentifier(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserIdentifier', []);

        return parent::getUserIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(string $prenom): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(?string $adresse): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getCp(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCp', []);

        return parent::getCp();
    }

    /**
     * {@inheritDoc}
     */
    public function setCp(?string $cp): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCp', [$cp]);

        return parent::setCp($cp);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille(?string $ville): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccueil(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccueil', []);

        return parent::getAccueil();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccueil(?string $accueil): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccueil', [$accueil]);

        return parent::setAccueil($accueil);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone(?string $telephone): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getNb(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNb', []);

        return parent::getNb();
    }

    /**
     * {@inheritDoc}
     */
    public function setNb(?string $nb): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNb', [$nb]);

        return parent::setNb($nb);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnimaux(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnimaux', []);

        return parent::getAnimaux();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnimaux(?string $animaux): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnimaux', [$animaux]);

        return parent::setAnimaux($animaux);
    }

    /**
     * {@inheritDoc}
     */
    public function getSterilise(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSterilise', []);

        return parent::getSterilise();
    }

    /**
     * {@inheritDoc}
     */
    public function setSterilise(?string $sterilise): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSterilise', [$sterilise]);

        return parent::setSterilise($sterilise);
    }

    /**
     * {@inheritDoc}
     */
    public function getChat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChat', []);

        return parent::getChat();
    }

    /**
     * {@inheritDoc}
     */
    public function setChat(?string $chat): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChat', [$chat]);

        return parent::setChat($chat);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuarantaine(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuarantaine', []);

        return parent::getQuarantaine();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuarantaine(?string $quarantaine): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuarantaine', [$quarantaine]);

        return parent::setQuarantaine($quarantaine);
    }

    /**
     * {@inheritDoc}
     */
    public function getJournee(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJournee', []);

        return parent::getJournee();
    }

    /**
     * {@inheritDoc}
     */
    public function setJournee(?string $journee): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJournee', [$journee]);

        return parent::setJournee($journee);
    }

    /**
     * {@inheritDoc}
     */
    public function getVacances(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVacances', []);

        return parent::getVacances();
    }

    /**
     * {@inheritDoc}
     */
    public function setVacances(?string $vacances): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVacances', [$vacances]);

        return parent::setVacances($vacances);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibre', []);

        return parent::getLibre();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibre(?string $libre): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibre', [$libre]);

        return parent::setLibre($libre);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssurance(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssurance', []);

        return parent::getAssurance();
    }

    /**
     * {@inheritDoc}
     */
    public function setAssurance(?string $assurance): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssurance', [$assurance]);

        return parent::setAssurance($assurance);
    }

    /**
     * {@inheritDoc}
     */
    public function getVeto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVeto', []);

        return parent::getVeto();
    }

    /**
     * {@inheritDoc}
     */
    public function setVeto(?string $veto): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVeto', [$veto]);

        return parent::setVeto($veto);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutre', []);

        return parent::getAutre();
    }

    /**
     * {@inheritDoc}
     */
    public function setAutre(?string $autre): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutre', [$autre]);

        return parent::setAutre($autre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNon(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNon', []);

        return parent::getNon();
    }

    /**
     * {@inheritDoc}
     */
    public function setNon(?string $non): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNon', [$non]);

        return parent::setNon($non);
    }

}
