<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Libre extends \App\Entity\Libre implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Libre' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Libre' . "\0" . 'lieu', '' . "\0" . 'App\\Entity\\Libre' . "\0" . 'carte', '' . "\0" . 'App\\Entity\\Libre' . "\0" . 'histoire', '' . "\0" . 'App\\Entity\\Libre' . "\0" . 'nourrice', '' . "\0" . 'App\\Entity\\Libre' . "\0" . 'aide', '' . "\0" . 'App\\Entity\\Libre' . "\0" . 'nombreChat'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Libre' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Libre' . "\0" . 'lieu', '' . "\0" . 'App\\Entity\\Libre' . "\0" . 'carte', '' . "\0" . 'App\\Entity\\Libre' . "\0" . 'histoire', '' . "\0" . 'App\\Entity\\Libre' . "\0" . 'nourrice', '' . "\0" . 'App\\Entity\\Libre' . "\0" . 'aide', '' . "\0" . 'App\\Entity\\Libre' . "\0" . 'nombreChat'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Libre $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getLieu(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieu', []);

        return parent::getLieu();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieu(?string $lieu): \App\Entity\Libre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieu', [$lieu]);

        return parent::setLieu($lieu);
    }

    /**
     * {@inheritDoc}
     */
    public function getCarte(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCarte', []);

        return parent::getCarte();
    }

    /**
     * {@inheritDoc}
     */
    public function setCarte(?string $carte): \App\Entity\Libre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCarte', [$carte]);

        return parent::setCarte($carte);
    }

    /**
     * {@inheritDoc}
     */
    public function getHistoire(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHistoire', []);

        return parent::getHistoire();
    }

    /**
     * {@inheritDoc}
     */
    public function setHistoire(?string $histoire): \App\Entity\Libre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHistoire', [$histoire]);

        return parent::setHistoire($histoire);
    }

    /**
     * {@inheritDoc}
     */
    public function getNourrice(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNourrice', []);

        return parent::getNourrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setNourrice(?string $nourrice): \App\Entity\Libre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNourrice', [$nourrice]);

        return parent::setNourrice($nourrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getAide(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAide', []);

        return parent::getAide();
    }

    /**
     * {@inheritDoc}
     */
    public function setAide(?bool $aide): \App\Entity\Libre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAide', [$aide]);

        return parent::setAide($aide);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreChat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreChat', []);

        return parent::getNombreChat();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreChat(?string $nombreChat): \App\Entity\Libre
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreChat', [$nombreChat]);

        return parent::setNombreChat($nombreChat);
    }

}
